- hosts: all
  become: yes
  roles: 
    - configuration
- hosts: frontends
  become: yes
  roles: 
    - lb
- hosts: apps
  become: yes
  roles:
    - tomcat
- hosts: appdbs
  become: yes
  roles:
    - postgres
- hosts: app1.5cb5.internal
  become: yes
  roles:
    - web_app
- hosts: app2.5cb5.internal
  become: yes
  roles:
    - web_app2

